### ISSUE TITLE
BUILD SEAECH DELEGATE THAT THE USER CAN SEAERCH THE JOB HE WANT

### ISSUE THREAD

**Issue by ENG-CJ** [ENG-CJ/Job-Finder-App#7]
**Tasks**
- [x] Show search delegate bar
- [x] decorate search delegate
- [x] build suggestions and results when the user searches the job he want
- [x] build action and leading for this delegate
